### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/PathSimAnalysis#15]
With python 3.12 support added in #11 we should make a new release so we can have py3.12 wheels on conda-forge.

**Comment by orbeckst** [comment]
I'll do a release.

**Comment by orbeckst** [comment]
@IAlibay are you working on the release? I just saw the 1.1.0 tag appear. If you're in the middle of it I won't get in your way, otherwise I'll be happy to do the rest, basically using https://github.com/MDAnalysis/mdanalysis/wiki/Guide-for-Maintainers as initial guidance.

**Comment by IAlibay** [comment]
Yeah sorry, I should have mentioned. I thought if all that was needed was a tag and a click for the release I might as well get it done whilst I had the repo open 😅

**Comment by orbeckst** [comment]
No worries, thanks for doing it!

**Comment by IAlibay** [comment]
And done !
