### ISSUE TITLE
Python 3.9 CI failing

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/PathSimAnalysis#18]
The scheduled CI runs with Python 3.9 are failing: https://github.com/MDAnalysis/PathSimAnalysis/actions/runs/8405477394/job/23018255774

  ERROR: Package 'mdanalysis' requires a different Python: 3.9.19 not in '>=3.10'

Either need to run it with the latest *supported* MDAnalysis or removed 3.9 tests.

**Comment by IAlibay** [comment]
related to this: https://github.com/MDAnalysis/cookiecutter-mdakit/issues/110
